---
title: "heatmap"
output: html_document
date: "2022-11-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(highcharter)
library(corrplot)
library(heatmaply)
library(tidyverse)
library(jsonlite)
library(tidygraph)
library(ggraph)
library(influential)
library(DPpack)
theme_set(theme_bw())
```

```{r}
dataUU <- read.table("https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/13_AdjacencyUndirectedUnweighted.csv", header=TRUE)
```


```{r}
word_list = read.table("./dataset/functionwords_list.txt", head=FALSE)
word_list <- as.matrix(word_list)
```


```{r}
book_names = c("austen_2", 
               "austen_4", 
               "dickens_1", 
               "dickens_4",
               "shakespeare_1",
               "shakespeare_5",
               "twain_1",
               "twain_4")

book_fullnames = c("Jane Austen, Emma",
                   "Jane Austen, Pride and Prejudice",
                   "Charles Dickens, A Christmas Carol",
                   "Charles Dickens, Oliver Twist",
                   "William Shakespeare, Hamlet",
                   "William Shakespeare, Romeo and Juliet",
                   "Mark Twain, Adventures of Huckleberry Finn",
                   "Mark Twain, The Adventures of Tom Sawyer")
```


```{r}
i = 1
book_name = paste0("./dataset/", book_names[i], ".txt")
book = read.table(book_name, head=FALSE)
colnames(book) = word_list
row.names(book) = word_list

# Normalizing rows by row max
book <- data.frame(t(apply(book,1, function(x) if (max(x)==0) x else x/max(x))))
# book <- as.matrix(book)
```


```{r}

```







```{r}
ggraph(book, layout = "matrix") +
  geom_edge_tile() +
  coord_fixed() +
  ggtitle(book_fullnames[i]) +
  geom_conn_bundle(aes(colour=book, alpha=book))

  # geom_node_text(aes(label = word_list), x = -1, nudge_y = 0.5) +
  # geom_node_text(aes(label = word_list), y = -1, nudge_x = -0.5)

```
```{r}
databook = book
databook["from"]=word_list
# databook = cbind(word_list, databook)
```






















```{r}
# Transform the adjacency matrix in a long format
connect <- dataUU %>% 
  gather(key="to", value="value", -1) %>%
  mutate(to = gsub("\\.", " ",to)) %>%
  na.omit()

# Number of connection per person
c( as.character(connect$from), as.character(connect$to)) %>%
  as.tibble() %>%
  group_by(value) %>%
  summarize(n=n()) -> coauth
colnames(coauth) <- c("name", "n")

# Create a graph object with igraph
mygraph <- graph_from_data_frame( connect, vertices = coauth, directed = TRUE )

# Find community
com <- walktrap.community(mygraph)

#Reorder dataset and make the graph
coauth <- coauth %>% 
  mutate( grp = com$membership) %>%
  arrange(grp) %>%
  mutate(name=factor(name, name))

# keep only 10 first communities
coauth <- coauth %>% 
  filter(grp<16)

# keep only this people in edges
connect <- connect %>%
  filter(from %in% coauth$name) %>%
  filter(to %in% coauth$name)

# Add label angle
number_of_bar=nrow(coauth)
coauth$id = seq(1, nrow(coauth))
angle= 360 * (coauth$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
coauth$hjust <- ifelse(angle > 90 & angle<270, 1, 0)
coauth$angle <- ifelse(angle > 90 & angle<270, angle+180, angle)

# Create a graph object with igraph
mygraph <- graph_from_data_frame( connect, vertices = coauth, directed = FALSE )

# prepare a vector of n color in the viridis scale
mycolor <- colormap(colormap=colormaps$viridis, nshades=max(coauth$grp))
mycolor <- sample(mycolor, length(mycolor))

# Make the graph
ggraph(mygraph, layout="circle") + 
  geom_edge_link(edge_colour="black", edge_alpha=0.2, edge_width=0.3, fold=FALSE) +
  geom_node_point(aes(size=n, color=as.factor(grp), fill=grp), alpha=0.9) +
  scale_size_continuous(range=c(0.5,8)) +
  scale_color_manual(values=mycolor) +
  geom_node_text(aes(label=paste("    ",name,"    "), angle=angle, hjust=hjust), size=2.3, color="black") +
  theme_void() +
  theme(
    legend.position="none",
    plot.margin=unit(c(0,0,0,0), "null"),
    panel.spacing=unit(c(0,0,0,0), "null")
  ) +
  expand_limits(x = c(-1.2, 1.2), y = c(-1.2, 1.2)) 
```



```{r}
par(mfrow=c(2,4))
for (i in 1:length(book_names)){
  book_name = paste0("./dataset/", book_names[i], ".txt")
  print(book_name)
  book = read.table(book_name, head=FALSE)
  colnames(book) = word_list
  row.names(book) = word_list
  
  # Normalizing rows by row max
  book <-t(apply(book,1, function(x) if (max(x)==0) x else x/max(x)))
  book <- as.matrix(book)
  
  ggraph(book, layout = "matrix") +
    geom_edge_tile() +
    coord_fixed()
}
```


Directly draw heatmap. There are a lot of zero rows (white).

```{r}
heatmap(book)
```
If we delete the all zero rows and columns

```{r}
data = book
data = data[which(rowSums(book) > 0),]
data = data[,which(colSums(book) > 0)]
heatmap(data)
```

Another type of heatmap, but only with first 20 words

```{r}
K = 20
data = book[1:K,1:K]
heatmaply(data, 
  dendrogram = "column",
  xlab = "", ylab = "", 
  main = "",
  scale = "none",
  # margins = c(60,100,40,20),
  grid_color = "white",
  grid_width = 0.000000001,
  titleX = TRUE,
  hide_colorbar = FALSE,
  branches_lwd = 0.01,
  label_names = c("From", "To:", "Value"),
  fontsize_row = 6, fontsize_col = 6,
  labCol = colnames(data),
  labRow = rownames(data),
  heatmap_layers = theme(axis.line=element_blank())
)
```
It is hard to show 200+ words at the same time. The following is the K=100 heatmap

```{r}
K = 100
data = book
data = data[which(rowSums(book) > 0),]
data = data[,which(colSums(book) > 0)]
data = data[1:K,1:K]
heatmaply(data, 
  dendrogram = "column",
  xlab = "", ylab = "", 
  main = "",
  scale = "none",
  # margins = c(60,100,40,20),
  grid_color = "white",
  grid_width = 0.000000001,
  titleX = TRUE,
  hide_colorbar = FALSE,
  branches_lwd = 0.01,
  label_names = c("From", "To:", "Value"),
  fontsize_row = 6, fontsize_col = 6,
  labCol = colnames(data),
  labRow = rownames(data),
  heatmap_layers = theme(axis.line=element_blank())
)
```
If we use correlation plot. Row and column labels are not clear.


```{r}
corrplot(book, 'square', tl.cex=0.2)
```



